### ISSUE TITLE
在Windows下IMiniCrack打开后点击选择目录闪退

### ISSUE THREAD

**Issue by LeviClapham** [o0x1024/IMiniCrack#2]

**Comment by o0x1024** [comment]
详情的环境信息可以贴一下么？

**Comment by o0x1024** [comment]
webview2 有没有安装呢?

**Comment by o0x1024** [comment]
下载的是最新版本么？

**Comment by vvsopk** [comment]
我这边也是这个问题，点击选择目录闪退
![image](https://github.com/o0x1024/IMiniCrack/assets/95007437/48592b56-ff30-44b9-85fb-ed5dd6afe480)
用的是最新版本，win10环境

**Comment by o0x1024** [comment]
> 我这边也是这个问题，点击选择目录闪退 ![image](https://private-user-images.githubusercontent.com/95007437/254206931-48592b56-ff30-44b9-85fb-ed5dd6afe480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Njc2MzcsIm5iZiI6MTcxNTY2NzMzNywicGF0aCI6Ii85NTAwNzQzNy8yNTQyMDY5MzEtNDg1OTJiNTYtZmYzMC00NGI5LTg1ZmItZWQ1ZGQ2YWZlNDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA2MTUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5OTY4YzEzM2Q1YjU4YzI1YWUwNDI2NzA5ZjFhMTQ2MGFlNGIxZWU5ZjUyNWEzZjBlNjUwZmI4MWE0ODI0YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vt54Qvzx7rNTtcbcstZUuXcwI_MSXI_VvpRomtDU1EM) 用的是最新版本，win10环境

手动安装webview2试试  https://developer.microsoft.com/en-us/microsoft-edge/webview2
