### ISSUE TITLE
建议支持讲小程序文件直接拖入"小程序包路径"后，自动填写文件路径

### ISSUE THREAD

**Issue by vvsopk** [o0x1024/IMiniCrack#3]
文件拖入输入框后，自动识别路径与wxid
![image](https://github.com/o0x1024/IMiniCrack/assets/95007437/fb0add0b-5ad6-40f2-b52d-152c012ea0dd)
目前我这边windows10环境暂不支持相关使用，拖入后直接弹出页面，就变成这样了
![image](https://github.com/o0x1024/IMiniCrack/assets/95007437/3b2bf326-c1d4-43fa-b539-fe7cefe0cb30)

**Comment by o0x1024** [comment]
受限于框架的原因，目前无法支持
