### ISSUE TITLE
敏感信息扫描【查看详情】

### ISSUE THREAD

**Issue by chenmuyunxi** [o0x1024/IMiniCrack#4]
问题描述：敏感信息扫描完成后，查看信息详情，如果敏感信息所在的代码行过长，无法快速定位到敏感信息的位置。
期望需求：大佬能否在查看详情的时候添加个快速搜索的功能，帮助使用者快速搜索敏感信息关键字使用。

**Comment by o0x1024** [comment]
你下载最新版本即可，最新版本点开详情后直接定位到了敏感信息那一行

**Comment by chenmuyunxi** [comment]
> 你下载最新版本即可，最新版本点开详情后直接定位到了敏感信息那一行

好的，多谢！！！
